import type { Localized } from './types'
import type { OptionListId } from './option-lists'

export type FieldType =
  | 'text'
  | 'textarea'
  | 'date'
  | 'number'
  | 'select'
  | 'select_with_detail'
  | 'multi_select'
  | 'template'

export type TemplateSlot = { key: string; unit: Localized }

export type Field = {
  key: string // 'I.1', 'III.6.6' — нумерация исходной формы
  section: string // 'I' | 'II' | 'III' | 'IV' | 'V'
  block: string // ключ блока проверки, см. Task 5
  type: FieldType
  label: Localized
  hint: Localized | null
  example: string | null
  required: boolean
  optionList: OptionListId | null
  templateText: Localized | null
  templateSlots: TemplateSlot[]
  /**
   * Option ids of this field's own `optionList` that require the clarifying
   * `detail` text even though the option itself is `plain()` (not
   * `requiresDetail`) in `option-lists.ts`. Lives here, not in a private map
   * inside `validation.ts`, because both the validator and `FieldInput` need
   * to agree on which options demand a detail — see `III.2.4`, whose
   * `airlineAccess` options are all `plain()` yet the "specific airlines"
   * choice is meaningless without naming them.
   */
  detailRequiredFor: string[]
}

const base = {
  hint: null,
  example: null,
  optionList: null,
  templateText: null,
  templateSlots: [],
  detailRequiredFor: [],
} satisfies Partial<Field>

export const FIELDS: Field[] = [
  {
    ...base,
    key: 'I.1',
    section: 'I',
    block: 'I',
    type: 'date',
    label: { en: 'Lounge Open Date*', ru: 'Дата открытия лаунжа*' },
    required: true,
  },
  {
    ...base,
    key: 'I.2',
    section: 'I',
    block: 'I',
    type: 'text',
    label: { en: 'Lounge Full Name*', ru: 'Полное название лаунжа*' },
    required: true,
  },
  {
    ...base,
    key: 'I.3',
    section: 'I',
    block: 'I',
    type: 'text',
    label: {
      en: 'Provider (Name of the company under which lounge is running )*',
      ru: 'Провайдер (название компании, управляющей лаунжем)*',
    },
    required: true,
  },
  {
    ...base,
    key: 'I.4',
    section: 'I',
    block: 'I',
    type: 'text',
    label: { en: 'Lounge Website Link', ru: 'Ссылка на сайт лаунжа' },
    required: true,
  },
  {
    ...base,
    key: 'I.5',
    section: 'I',
    block: 'I',
    type: 'textarea',
    label: {
      en: 'Company Registered Office Address  *',
      ru: 'Юридический адрес компании*',
    },
    required: true,
  },
  {
    ...base,
    key: 'I.6',
    section: 'I',
    block: 'I',
    type: 'text',
    label: {
      en: 'Name Of Authorized Person Who Has Signed The Agreement With Designation *',
      ru: 'Ф.И.О. и должность лица, подписавшего договор*',
    },
    required: true,
  },
  {
    ...base,
    key: 'I.7',
    section: 'I',
    block: 'I',
    type: 'text',
    label: { en: 'Country*', ru: 'Страна*' },
    required: true,
  },
  {
    ...base,
    key: 'I.8',
    section: 'I',
    block: 'I',
    type: 'text',
    label: { en: 'City*', ru: 'Город*' },
    required: true,
  },
  {
    ...base,
    key: 'I.9',
    section: 'I',
    block: 'I',
    type: 'text',
    label: { en: 'Airport*', ru: 'Аэропорт*' },
    required: true,
  },
  {
    ...base,
    key: 'I.10',
    section: 'I',
    block: 'I',
    type: 'text',
    label: { en: 'IATA Code*', ru: 'Код IATA*' },
    required: true,
  },
  {
    ...base,
    key: 'I.11',
    section: 'I',
    block: 'I',
    type: 'text',
    label: { en: 'Pin Code/Zip Code*', ru: 'Почтовый индекс*' },
    required: true,
  },
  {
    ...base,
    key: 'I.12',
    section: 'I',
    block: 'I',
    type: 'text',
    label: {
      en: 'Currency Accepted (INR/USD/EUR/Any Other) Please Mention*',
      ru: 'Принимаемая валюта (INR/USD/EUR/другая) — укажите*',
    },
    required: true,
  },
  {
    ...base,
    key: 'I.13',
    section: 'I',
    block: 'I',
    type: 'text',
    label: {
      en: 'Guest Fee Rate (Walk-in Price for Lounge access)*',
      ru: 'Тариф для гостей (цена при обращении без брони на доступ в лаунж)*',
    },
    required: true,
  },
  {
    ...base,
    key: 'I.14',
    section: 'I',
    block: 'I',
    type: 'number',
    label: { en: 'Tax Chargeable (%)', ru: 'Взимаемый налог (%)' },
    required: true,
  },
  {
    ...base,
    key: 'I.15',
    section: 'I',
    block: 'I',
    type: 'text',
    label: {
      en: 'DreamFolks B2B rates for Lounge Access',
      ru: 'Тарифы DreamFolks B2B на доступ в лаунж',
    },
    required: true,
  },
  {
    ...base,
    key: 'II.1.1',
    section: 'II',
    block: 'II.1',
    type: 'text',
    label: {
      en: 'Lounge Operations Manager Name (SPOC)',
      ru: 'Имя менеджера по операциям лаунжа (SPOC)',
    },
    required: true,
  },
  {
    ...base,
    key: 'II.1.2',
    section: 'II',
    block: 'II.1',
    type: 'text',
    label: {
      en: 'Contact Number - Lounge Operations Manager',
      ru: 'Контактный номер — менеджер по операциям лаунжа',
    },
    required: true,
  },
  {
    ...base,
    key: 'II.1.3',
    section: 'II',
    block: 'II.1',
    type: 'text',
    label: {
      en: 'Email Address - Lounge Operations Manager',
      ru: 'Электронная почта — менеджер по операциям лаунжа',
    },
    required: true,
  },
  {
    ...base,
    key: 'II.2.1',
    section: 'II',
    block: 'II.2',
    type: 'text',
    label: {
      en: 'Shift Mobile / Duty Phone Number',
      ru: 'Мобильный/дежурный номер смены',
    },
    required: true,
  },
  {
    ...base,
    key: 'II.2.2',
    section: 'II',
    block: 'II.2',
    type: 'text',
    label: {
      en: 'Alternative Operation Contact (name/email/phone)',
      ru: 'Альтернативный операционный контакт (имя/email/телефон)',
    },
    required: true,
  },
  {
    ...base,
    key: 'II.2.3',
    section: 'II',
    block: 'II.2',
    type: 'text',
    label: {
      en: 'Preferred Communication Channel (phone/email/whatsApp/other messenger)',
      ru: 'Предпочитаемый канал связи (телефон/email/WhatsApp/другой мессенджер)',
    },
    required: true,
  },
  {
    ...base,
    key: 'II.3.1',
    section: 'II',
    block: 'II.3',
    type: 'text',
    label: { en: 'Finance SPOC- Name', ru: 'Финансовый SPOC — имя' },
    required: true,
  },
  {
    ...base,
    key: 'II.3.2',
    section: 'II',
    block: 'II.3',
    type: 'text',
    label: { en: 'Finance SPOC- Contact No', ru: 'Финансовый SPOC — контактный номер' },
    required: true,
  },
  {
    ...base,
    key: 'II.3.3',
    section: 'II',
    block: 'II.3',
    type: 'text',
    label: {
      en: 'Finance SPOC- Email address',
      ru: 'Финансовый SPOC — электронная почта',
    },
    required: true,
  },
  {
    ...base,
    key: 'II.4.1',
    section: 'II',
    block: 'II.4',
    type: 'text',
    label: {
      en: 'Telephone- Landline/Fixline No -Lounge (If Any)',
      ru: 'Телефон — стационарный номер лаунжа (если есть)',
    },
    required: false,
  },
  {
    ...base,
    key: 'II.4.2',
    section: 'II',
    block: 'II.4',
    type: 'text',
    label: { en: 'Fax Number (If Any)', ru: 'Номер факса (если есть)' },
    required: false,
  },
  {
    ...base,
    key: 'III.1.1',
    section: 'III',
    block: 'III.1',
    type: 'text',
    label: { en: 'Lounge Operating Hours', ru: 'Часы работы лаунжа' },
    example: 'Monday – Saturday: 00:00 – 23:59\nSunday: 03:00 – 23:59',
    required: true,
  },
  {
    ...base,
    key: 'III.1.2',
    section: 'III',
    block: 'III.1',
    type: 'select_with_detail',
    label: { en: 'Seasonal schedule changes', ru: 'Сезонные изменения графика работы' },
    example: 'Yes → Closed from 30 September to 01 April\nOR\nYes → From 1 June to 30 September: Monday-Sunday 05:00 – 01:00',
    required: true,
    optionList: 'yesSpecifyNo',
  },
  {
    ...base,
    key: 'III.1.3',
    section: 'III',
    block: 'III.1',
    type: 'text',
    label: { en: 'Peak Hours', ru: 'Часы пиковой нагрузки' },
    example: 'Daily: 06:00 – 09:00 and 17:00 – 21:00',
    required: true,
  },
  {
    ...base,
    key: 'III.1.4',
    section: 'III',
    block: 'III.1',
    type: 'textarea',
    label: { en: 'Deep Cleaning Schedule', ru: 'График глубокой уборки' },
    example: 'Every day: 14:30 – 15:00\nOR\nAdditional deep cleaning every first Monday of the month: 22:00 – 23:30',
    required: true,
  },
  {
    ...base,
    key: 'III.2.1',
    section: 'III',
    block: 'III.2',
    type: 'template',
    label: {
      en: 'Earliest Access Time Before Departure (hours)',
      ru: 'За сколько часов до вылета открыт доступ',
    },
    hint: {
      en: 'If no restriction applies, enter 0.',
      ru: 'Если ограничений нет, укажите 0.',
    },
    example: 'Access is permitted 3 hours prior to scheduled flight departure.',
    required: true,
    templateText: {
      en: 'Access is permitted (  ) hours prior to scheduled flight departure.',
      ru: 'Доступ разрешён за (  ) часов до вылета по расписанию.',
    },
    templateSlots: [{ key: 'hours', unit: { en: 'hours', ru: 'часов' } }],
  },
  {
    ...base,
    key: 'III.2.2',
    section: 'III',
    block: 'III.2',
    type: 'number',
    label: {
      en: 'Duration of Stay in Single Visit (For The Customer/Passenger) (hours)',
      ru: 'Продолжительность одного визита (для гостя/пассажира) (часы)',
    },
    example: '3 hours',
    required: true,
  },
  {
    ...base,
    key: 'III.2.3',
    section: 'III',
    block: 'III.2',
    type: 'select',
    label: { en: 'Re-entry Allowed', ru: 'Повторный вход разрешён' },
    example: 'Yes',
    required: true,
    optionList: 'yesNo',
  },
  {
    ...base,
    key: 'III.2.4',
    section: 'III',
    block: 'III.2',
    type: 'select_with_detail',
    label: {
      en: 'Airline-Specific Access Restrictions',
      ru: 'Ограничения по авиакомпаниям',
    },
    example: 'Specific airlines passengers allowed\nFor Turkish Airlines passengers only',
    required: true,
    optionList: 'airlineAccess',
    detailRequiredFor: ['specific'],
  },
  {
    ...base,
    key: 'III.2.5',
    section: 'III',
    block: 'III.2',
    type: 'select_with_detail',
    label: { en: 'Airline Crew Access', ru: 'Доступ для экипажа авиакомпаний' },
    hint: {
      en: 'Please specify if Allowed under specific conditions',
      ru: 'Уточните, если разрешено при определённых условиях',
    },
    example: 'Allowed',
    required: true,
    optionList: 'allowedConditional',
  },
  {
    ...base,
    key: 'III.3.1',
    section: 'III',
    block: 'III.3',
    type: 'template',
    label: {
      en: 'Free Children Access Policy',
      ru: 'Политика бесплатного доступа для детей',
    },
    example: 'No Charge for Children under (  2  ) years old.',
    required: true,
    templateText: {
      en: 'No Charge for Children under (    ) years old.',
      ru: 'Бесплатно для детей младше (    ) лет.',
    },
    templateSlots: [{ key: 'age', unit: { en: 'years old', ru: 'лет' } }],
  },
  {
    ...base,
    key: 'III.3.2',
    section: 'III',
    block: 'III.3',
    type: 'select',
    label: {
      en: 'Unaccompanied Children Policy (minimum age, if allowed)',
      ru: 'Политика для детей без сопровождения (минимальный возраст, если разрешено)',
    },
    example: 'Allowed\nChildren from (10 ) years old can enter unaccompanied.',
    required: true,
    optionList: 'allowedNotAllowed',
    templateText: {
      en: 'Children from (  ) years old can enter unaccompanied.',
      ru: 'Дети с (  ) лет могут входить без сопровождения.',
    },
    templateSlots: [{ key: 'age', unit: { en: 'years old', ru: 'лет' } }],
  },
  {
    ...base,
    key: 'III.3.3',
    section: 'III',
    block: 'III.3',
    type: 'template',
    label: {
      en: 'Price for Children Access (Walk-in price and age group)',
      ru: 'Стоимость доступа для детей (цена без брони и возрастная группа)',
    },
    example: 'Child rate: Children from 3 to 12 years old: USD 18 per child (walk-in price).\nAdult rate: Children 13 years and older: Full adult price – USD 35.',
    required: true,
    templateText: {
      en: 'Child rate: children from (  ) to (  ) years old \nAdult rate: children (  ) years and older',
      ru: 'Детский тариф: дети от (  ) до (  ) лет \nВзрослый тариф: с (  ) лет',
    },
    templateSlots: [
      { key: 'childFrom', unit: { en: 'years old', ru: 'лет' } },
      { key: 'childTo', unit: { en: 'years old', ru: 'лет' } },
      { key: 'adultFrom', unit: { en: 'years and older', ru: 'лет и старше' } },
    ],
  },
  {
    ...base,
    key: 'III.4.1',
    section: 'III',
    block: 'III.4',
    type: 'select_with_detail',
    label: { en: 'Stroller / Pram Access', ru: 'Доступ с детской коляской' },
    example: 'Allowed\nFor safety reasons, they must not block emergency exits or walkways.',
    required: true,
    optionList: 'allowedNotAllowedOther',
  },
  {
    ...base,
    key: 'III.4.2',
    section: 'III',
    block: 'III.4',
    type: 'select_with_detail',
    label: { en: 'Pet Access', ru: 'Доступ с домашними животными' },
    example: 'Allowed\nPets should be transported in a hand carrier.',
    required: true,
    optionList: 'allowedNotAllowedOther',
  },
  {
    ...base,
    key: 'III.4.3',
    section: 'III',
    block: 'III.4',
    type: 'select_with_detail',
    label: { en: 'Assistance Animals Access', ru: 'Доступ с животными-помощниками' },
    example: 'Allowed\nGuide dogs are allowed. Must be on leash and vaccinated.',
    required: true,
    optionList: 'allowedNotAllowedOther',
  },
  {
    ...base,
    key: 'III.4.4',
    section: 'III',
    block: 'III.4',
    type: 'select_with_detail',
    label: {
      en: 'Dress Code / Attire Restrictions',
      ru: 'Дресс-код / ограничения на одежду',
    },
    example: 'Yes → The following items are not permitted: Sleepwear or pajamas/Bare feet',
    required: true,
    optionList: 'yesSpecifyNo',
  },
  {
    ...base,
    key: 'III.4.5',
    section: 'III',
    block: 'III.4',
    type: 'select',
    label: {
      en: 'Free Companion Access for Passengers with Special Needs',
      ru: 'Бесплатный доступ для сопровождающего пассажиров с особыми потребностями',
    },
    example: 'Yes',
    required: true,
    optionList: 'yesNo',
  },
  {
    ...base,
    key: 'III.4.6',
    section: 'III',
    block: 'III.4',
    type: 'select',
    label: {
      en: 'Photo & Video inside the lounge',
      ru: 'Фото- и видеосъёмка внутри лаунжа',
    },
    example: 'Allowed',
    required: true,
    optionList: 'allowedNotAllowed',
  },
  {
    ...base,
    key: 'III.4.7',
    section: 'III',
    block: 'III.4',
    type: 'textarea',
    label: { en: 'Other Restrictions', ru: 'Прочие ограничения' },
    hint: {
      en: 'Please don’t miss this field',
      ru: 'Пожалуйста, не пропустите это поле',
    },
    example: 'Outside food and beverages are not permitted.',
    required: true,
  },
  {
    ...base,
    key: 'III.5.1',
    section: 'III',
    block: 'III.5',
    type: 'textarea',
    label: {
      en: 'Exact location of the lounge/Directions to reach',
      ru: 'Точное расположение лаунжа / как добраться',
    },
    hint: {
      en: 'Please add more details (if any)',
      ru: 'Добавьте дополнительные детали (если есть)',
    },
    example: 'Please follow the example provided:\nLocated in Main Terminal, after security check and passport control, Mezzanine Floor, between Terminals 1 and 2. Turn left after passport control. The lounge is on the right-hand side near Gate 12 and near "iStore" shop.',
    required: true,
  },
  {
    ...base,
    key: 'III.5.2',
    section: 'III',
    block: 'III.5',
    type: 'select',
    label: { en: 'Floor', ru: 'Этаж' },
    example: 'Ground',
    required: true,
    optionList: 'floor',
  },
  {
    ...base,
    key: 'III.5.3',
    section: 'III',
    block: 'III.5',
    type: 'text',
    label: {
      en: 'Hall / Concourse (if applicable)',
      ru: 'Зал / галерея (если применимо)',
    },
    example: 'Concourse B, Pier A',
    required: false,
  },
  {
    ...base,
    key: 'III.5.4',
    section: 'III',
    block: 'III.5',
    type: 'text',
    label: {
      en: 'Closest Boarding Gate (near Gate No/Lift No)',
      ru: 'Ближайший выход на посадку (номер выхода/лифта)',
    },
    hint: {
      en: 'Please don’t miss this field',
      ru: 'Пожалуйста, не пропустите это поле',
    },
    example: 'Near Gate 12 / Lift 3',
    required: true,
  },
  {
    ...base,
    key: 'III.5.5',
    section: 'III',
    block: 'III.5',
    type: 'text',
    label: {
      en: 'Nearby Landmarks (near Shops, Restaurant, facilities, etc.)',
      ru: 'Ближайшие ориентиры (магазины, рестораны, объекты и т.д.)',
    },
    hint: {
      en: 'Please don’t miss this field',
      ru: 'Пожалуйста, не пропустите это поле',
    },
    example: 'Next to Starbucks, near the information desk.',
    required: true,
  },
  {
    ...base,
    key: 'III.6.1',
    section: 'III',
    block: 'III.6',
    type: 'select',
    label: {
      en: 'Terminal Type  (Domestic/International/Both)',
      ru: 'Тип терминала (внутренний/международный/оба)',
    },
    example: 'Domestic/International',
    required: true,
    optionList: 'terminalType',
  },
  {
    ...base,
    key: 'III.6.2',
    section: 'III',
    block: 'III.6',
    type: 'select_with_detail',
    label: {
      en: 'Terminal Name (T1/T2/T3/T4/T5/Main Terminal/Satellite)',
      ru: 'Название терминала (T1/T2/T3/T4/T5/основной терминал/сателлит)',
    },
    example: 'T3',
    required: true,
    optionList: 'terminalName',
  },
  {
    ...base,
    key: 'III.6.3',
    section: 'III',
    block: 'III.6',
    type: 'select',
    label: { en: 'Before / After Security Check', ru: 'До/после досмотра' },
    example: 'Before SHA',
    required: true,
    optionList: 'securityCheck',
  },
  {
    ...base,
    key: 'III.6.4',
    section: 'III',
    block: 'III.6',
    type: 'select',
    label: { en: 'Airside / Landside', ru: 'Стерильная зона / общая зона' },
    example: 'Airside',
    required: true,
    optionList: 'airsideLandside',
  },
  {
    ...base,
    key: 'III.6.5',
    section: 'III',
    block: 'III.6',
    type: 'select',
    label: { en: 'Before / After Immigration', ru: 'До/после паспортного контроля' },
    example: 'After Immigration',
    required: true,
    optionList: 'immigration',
  },
  {
    ...base,
    key: 'III.6.6',
    section: 'III',
    block: 'III.6',
    type: 'multi_select',
    label: { en: 'Arrival / Departure / Transit', ru: 'Прилёт / Вылет / Транзит' },
    hint: {
      en: 'Please indicate all applicable zones (e.g. Departure, Transit)',
      ru: 'Укажите все применимые зоны (например, Вылет, Транзит)',
    },
    example: 'Departure/Transit',
    required: true,
    optionList: 'zone',
  },
  {
    ...base,
    key: 'III.7.1',
    section: 'III',
    block: 'III.7',
    type: 'text',
    label: {
      en: 'Terminals Accessible From (Name all the terminals the lounge can be accessed from)',
      ru: 'Терминалы, из которых доступен лаунж (укажите все терминалы)',
    },
    hint: {
      en: 'Please don’t miss this field',
      ru: 'Пожалуйста, не пропустите это поле',
    },
    example: 'T1, T2, Main Terminal',
    required: true,
  },
  {
    ...base,
    key: 'III.7.2',
    section: 'III',
    block: 'III.7',
    type: 'select_with_detail',
    label: {
      en: 'Access Method from Other Terminals',
      ru: 'Способ доступа из других терминалов',
    },
    example: 'Other (Please specify→):\nWalking and Shuttle Bus',
    required: true,
    optionList: 'transferMethod',
  },
  {
    ...base,
    key: 'III.7.3',
    section: 'III',
    block: 'III.7',
    type: 'number',
    label: {
      en: 'Transfer Time from Other Terminals (min)',
      ru: 'Время в пути из других терминалов (мин)',
    },
    example: 'By shuttle bus (every 5 mins) - 3 mins\nWalking - approximately 10 minutes',
    required: true,
  },
  {
    ...base,
    key: 'III.7.4',
    section: 'III',
    block: 'III.7',
    type: 'select',
    label: {
      en: 'Whether Transit Passengers Can Access the Lounge',
      ru: 'Могут ли транзитные пассажиры попасть в лаунж',
    },
    example: 'Yes',
    required: true,
    optionList: 'yesNo',
  },
  {
    ...base,
    key: 'III.8.1',
    section: 'III',
    block: 'III.8',
    type: 'number',
    label: { en: 'Outlet Seating Capacity', ru: 'Вместимость (количество мест)' },
    example: '60 seats',
    required: true,
  },
  {
    ...base,
    key: 'III.8.2',
    section: 'III',
    block: 'III.8',
    type: 'select_with_detail',
    label: { en: 'Overcrowding Policy', ru: 'Политика при переполненности' },
    example: 'Other (Please specify→)\nIf the lounge reaches full capacity, guests may be directed to a nearby partner lounge.',
    required: true,
    optionList: 'overcrowding',
  },
  {
    ...base,
    key: 'IV.1',
    section: 'IV',
    block: 'IV',
    type: 'text',
    label: {
      en: 'Window/Door Stickers with Logo',
      ru: 'Наклейки на окна/двери с логотипом',
    },
    required: true,
  },
  {
    ...base,
    key: 'IV.2',
    section: 'IV',
    block: 'IV',
    type: 'text',
    label: { en: 'Common Signage', ru: 'Общая вывеска/указатели' },
    required: true,
  },
  {
    ...base,
    key: 'IV.3',
    section: 'IV',
    block: 'IV',
    type: 'text',
    label: {
      en: 'Desk Stand (Physical Standee) with Logo',
      ru: 'Настольная стойка (стенд) с логотипом',
    },
    required: true,
  },
  {
    ...base,
    key: 'IV.4',
    section: 'IV',
    block: 'IV',
    type: 'textarea',
    label: {
      en: 'Address for Posting Marketing Materials',
      ru: 'Адрес для отправки маркетинговых материалов',
    },
    required: true,
  },
  {
    ...base,
    key: 'V',
    section: 'V',
    block: 'V',
    type: 'date',
    label: {
      en: 'Lounge Validity - Term End date with Airport Authorities',
      ru: 'Срок действия соглашения с администрацией аэропорта',
    },
    required: true,
  },
]

export function fieldByKey(key: string): Field | undefined {
  return FIELDS.find((f) => f.key === key)
}
